import './globals.css'
import { Titillium_Web } from 'next/font/google'

const tilliumWeb = Titillium_Web({ weight: ["700", "600", "400"], subsets: ["latin"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={tilliumWeb.className}>{children}</body>
    </html>
  )
}
